package net.vakror.asm.seal;

import static net.vakror.asm.seal.SealTooltip.*;
import static net.vakror.asm.seal.SealTooltip.SealTooltipComponentBuilder.ColorCode.*;

public class SealTooltips {
    public static SealTooltip AXING = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.offensive())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 4")
                    .addPartWithNewline("When Activated: ")
                    .addPartWithNewline("   • Strips Wood", GREEN)
                    .addPartWithNewline("   • Mines Wood Blocks Faster", GREEN)
                    .addPartWithNewline("       + Mines With Diamond Tier", GREEN)
                    .addPartWithNewline("   • Damage + 9", GREEN)
                    .addPartWithNewline("   • Swing Speed -4", RED)
                    .addPartWithNewline("")
                    .addPartWithNewline("Compatible With:")
                    .addPartWithNewline("   • Damage Seal | Tier 1", GOLD)
                    .addPartWithNewline("   • Haste Seal | Tiers 1&2", GOLD).build())
            .build();

    public static SealTooltip SWORDING = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.offensive())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 4")
                    .addPartWithNewline("When Activated: ")
                    .addPartWithNewline("   • Damage + 7", GREEN)
                    .addPartWithNewline("   • Swing Speed -3", RED)
                    .addPartWithNewline("")
                    .addPartWithNewline("Compatible With:")
                    .addPartWithNewline("   • Damage Seal | Tier 1", GOLD)
                    .addPartWithNewline("   • Looting Seal | Tier 1", GOLD).build())
            .build();
    public static SealTooltip PICKING = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.passive())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 3")
                    .addPartWithNewline("When Activated: ")
                    .addPartWithNewline("   • Mines Stone Blocks Faster", GREEN)
                    .addPartWithNewline("       + Mines With Diamond Tier", GREEN)
                    .addPartWithNewline("   • Damage +4.5", GREEN)
                    .addPartWithNewline("   • Swing Speed -2", RED)
                    .addPartWithNewline("")
                    .addPartWithNewline("Compatible With:")
                    .addPartWithNewline("   • Haste Seal | Tiers 1&2", GOLD)
                    .addPartWithNewline("   • Smelting Seal", GOLD)
                    .addPartWithNewline("   • Vein Mine Seal | All Tiers", GOLD)
                    .addPartWithNewline("   • Fortune Seal | Tiers 1-3", GOLD)
                    .addPartWithNewline("   • Silk Touch Seal", GOLD)
                    .build())
            .build();
    public static SealTooltip HOEING = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.passive())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 3")
                    .addPartWithNewline("When Activated: ")
                    .addPartWithNewline("   • Tills Dirt", GREEN)
                    .addPartWithNewline("   • Mines Natural (Leaf & Hay...) Blocks Faster", GREEN)
                    .addPartWithNewline("       + Mines With Diamond Tier", GREEN)
                    .addPartWithNewline("   • Damage +1", GREEN)
                    .addPartWithNewline("   • Swing Speed -2", RED)
                    .addPartWithNewline("")
                    .addPartWithNewline("Compatible With:")
                    .addPartWithNewline("   • Haste Seal | Tiers 1&2", GOLD)
                    .addPartWithNewline("   • Replant Seal", GOLD)
                    .addPartWithNewline("   • Harvest AOE Seal | Tier 1", GOLD)
                    .addPartWithNewline("   • Farm AOE Seal | Tiers 1&2", GOLD).build())
            .build();
    public static SealTooltip HASTE = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.amplifying())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 5")
                    .addPartWithNewline("When On Wand: ")
                    .addPartWithNewline("   • Multiplies Mining Speed By 2x", GREEN).build())
            .build();
    public static SealTooltip STACK_SIZE = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.amplifying())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 6")
                    .addPartWithNewline("When On Wand: ")
                    .addPartWithNewline("   • Increases Stack Size In Sack By 2x", GREEN).build())
            .build();
    public static SealTooltip WIDTH = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.amplifying())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 4")
                    .addPartWithNewline("When On Wand: ")
                    .addPartWithNewline("   • Adds 1 Column To Sack", GREEN).build())
            .build();
    public static SealTooltip HEIGHT = new SealTooltipBuilder()
            .addPart(SealTooltipComponent.amplifying())
            .addPart(new SealTooltipComponentBuilder()
                    .addPartWithNewline("")
                    .addTierWithNewline(1)
                    .addPartWithNewline("Max Tier: 4")
                    .addPartWithNewline("When On Wand: ")
                    .addPartWithNewline("   • Adds 1 Row To Sack", GREEN).build())
            .build();
}
